### ISSUE TITLE
Q21 feedback : Rename "unreachable" to "never"

### ISSUE THREAD

**Issue by Mazwak** [dtolnay/rust-quiz#10]
I had a hard time to understand what is happening in the first print.

I could not found any information about the "unreachable" type. It turns out it is officially called the "never" type.

You might want to change the naming in the explanation.

**Comment by dtolnay** [comment]
Thanks! I changed the name and added a link to the standard library documentation in fd3524d2c012940745f58e3fdeac5f08ea8cf327.
