### ISSUE TITLE
Quiz #25 explanation not clear

### ISSUE THREAD

**Issue by rexpan** [dtolnay/rust-quiz#11]
I am a beginner to Rust lang.
I am not understand the explanation for Quiz #25

> On the first line of main, we call f() and perform an infallible match that binds no new variables. As no variables are declared on this line, there is no variable that could be the owner of the S returned by f() so that S is dropped at that point, printing 2.

Could you explain the above section with more detail and/or point to some related documents.

Thanks.

**Comment by dtolnay** [comment]
Thanks! I extended the explanation with a link in fdce1e2d20aeed2e7c05c62f68a7a6e12dd02e46. The `S` in `let S = f()` is a unit struct pattern (not a variable name) that matches a value of type `S` via [destructuring] but does not bind the value to any variable.

[destructuring]: https://doc.rust-lang.org/book/ch18-03-pattern-syntax.html#destructuring-to-break-apart-values
