### ISSUE TITLE
dead link 

### ISSUE THREAD

**Issue by lovasoa** [dtolnay/rust-quiz#16]
several questions refer to a FAQ entry that used to explain why rust doesn't have `--` and `++` operators, but the link seems to be dead:

https://www.rust-lang.org/en-US/faq.html#why-doesnt-rust-have-increment-and-decrement-operators

**Comment by lovasoa** [comment]
The two questions are # 16 and 17:

 https://github.com/dtolnay/rust-quiz/blob/962d33127ac387c0dffb6fbfbfa5b8fcefdf8d9e/questions/016-prefix-decrement.md

https://github.com/dtolnay/rust-quiz/blob/962d33127ac387c0dffb6fbfbfa5b8fcefdf8d9e/questions/017-unary-decrement.md

**Comment by dtolnay** [comment]
Thanks! Fixed.
https://dtolnay.github.io/rust-quiz/16
https://dtolnay.github.io/rust-quiz/17
