### ISSUE TITLE
Question involving FnMut closures with a Copy impl

### ISSUE THREAD

**Issue by dtolnay** [dtolnay/rust-quiz#37]
A tricky one from https://twitter.com/RReverser/status/1392917726541361161:

```rust
fn foo(mut f: impl FnMut() + Copy) {
    f();
}

fn bar(mut f: impl FnMut() + Copy) {
    f();
    foo(f);
    f();
    foo(f);
}

fn main() {
    let mut i = 0;
    bar(move || {
        i += 1;
        print!("{}", i);
    });
}
```

@RReverser might consent to this being turned into a quiz question verbatim. :pray:

**Comment by RReverser** [comment]
> @RReverser might consent to this being turned into a quiz question verbatim. 🙏

Totally! Someone suggested that in replies on Twitter, and I actually meant to raise an issue or PR myself, but haven't found time yet :)

**Comment by RReverser** [comment]
Feel free to use the explanation from follow-ups in the same thread too (or provide a custom one if that one's not clear enough, either way is fine by me): https://twitter.com/RReverser/status/1393347767163101184
