### ISSUE TITLE
Newb needs clarification for question 25, regarding "infallible match"

### ISSUE THREAD

**Issue by hoijui** [dtolnay/rust-quiz#39]
> On the first line of main, we call f() and perform an infallible match that binds no new variables.

referencing:

https://github.com/dtolnay/rust-quiz/blob/master/questions/025-unit-infallible-match.rs#L22

Why is this not binding a variable called `S` to the value returned from `f()`?
Where is the match?
I am totally lost there.

**Comment by tpoliaw** [comment]
As I understand it, the left hand side of any assignment is not necessarily a variable name, it is a pattern. When you do something like `let x = f()` you use `x` as a pattern that matches anything and captures the whole right hand side as `x`. In this case, the `S` is a pattern that matches any instance of the struct `S` but doesn't capture the variable. You could do something like `let x @ S = f()` which is a bit redundant but shows what the pattern matching is doing. The `S` is the pattern that irrefutably matches the result of `f()`, and `x` is the variable it is bound to.

It is similar to something like `if let None = foo() {}`. It doesn't assign a new variable called `None`, it matches the pattern.

Have a look at the rust book section on [Destructuring Structs](https://doc.rust-lang.org/book/ch18-03-pattern-syntax.html#destructuring-structs).

**Comment by hoijui** [comment]
soo.. if I would want to bind a new variable called `S` to the return value of the function `f()`, how would I do that then?

**Comment by tpoliaw** [comment]
I'm not sure you can. Trying to gives the compiler error `let bindings cannot shadow unit structs` and a link to [E0530](https://doc.rust-lang.org/error-index.html#E0530).

**Comment by dtolnay** [comment]
Local bindings (a.k.a. variables) are conventionally snake_case and type names including unit struct names are CamelCase, so this should never come up.

**Comment by hoijui** [comment]
I understand this, but I have to say... I am not .. seeing through it, still.
... does that mean, if I have `let S = f();`, and it could be an assignment or a match, then it will be a match?
and if there were no struct S, it would be an assignment?
match takes precedence over assignment?

**Comment by captchaKing** [comment]
To me it also looks weird. They could have used `let S{} = f();` for destructuring (pattern matching) of unit-like types. Would be so much cleaner.
And made `let S = f();` an error case -- <Type is used in inappropriate context>.
