### ISSUE TITLE
Link to repository once user has finished all questions

### ISSUE THREAD

**Issue by dtolnay** [dtolnay/rust-quiz#4]
Maybe in the footer:

> You have answered 26 of 26 questions correctly. [Contribute more questions!](https://github.com/dtolnay/rust-quiz)

**Comment by Diggsey** [comment]
It would be nice to show a completion page with some stats, eg. "you got X right first time, you took Y seconds per question, etc."

Maybe even some global stats, with a break-down per question, so we can see what questions people struggle with. Although this would require some persistent storage somewhere...
