### ISSUE TITLE
Idea: subpatterns and non-trivial patterns affect lifetimes

### ISSUE THREAD

**Issue by QuineDot** [dtolnay/rust-quiz#43]
[See this issue.](https://github.com/rust-lang/rust/issues/86989)

Fails:
```
fn f(mut x: &String) {
    x = &String::new();
}
```
Compiles:
```
fn f(mut x @ _: &String) {
    x = &String::new();
}

fn f((mut x,): (&String,)) {
    x = &String::new();
}
```

**Comment by dtolnay** [comment]
This seems to fall in the "does this program compile or does it not compile?" category that https://github.com/dtolnay/rust-quiz#contributing explains, so I don't think this would make a good quiz question. Thanks anyway for the suggestion!
