### ISSUE TITLE
How can I get notified if new quiz pop up?

### ISSUE THREAD

**Issue by MichaelScofield** [dtolnay/rust-quiz#48]
I really like these quiz and not want to miss any new quiz. So are there any subscriptions I can subscribe to?

Maybe we could use the Github's "release" feature: release a new version when there is a new quiz, so people could just watch this repo to get notified.

**Comment by dtolnay** [comment]
Sure thing, I can publish GitHub releases for all future questions, with a link to the new question on the website. Thank you, good idea.

**Comment by MichaelScofield** [comment]
Nice!
