### ISSUE TITLE
problem #10 - correcting explanation

### ISSUE THREAD

**Issue by amab8901** [dtolnay/rust-quiz#62]
Hi,

First of all, thank you for this amazing quiz. Very helpful and educational.

I solved quiz question #10, and the explanation says:
```
these names shadow each other
```
I don't think this is accurate. Here's why.

1. Compiler gives warnings that this one:
```
impl<'a> dyn Trait + 'a {
    fn f(&self) {
        print!("1");
    }
}
```
... isn't being used. When you remove this, the compiler stops giving warnings about it.

2. If you remove this...
```
impl Trait for bool {
    fn f(&self) {
        print!("2");
    }
}
```
.... then the code won't compile. This suggests that the code in point #1 above doesn't work.

**Comment by dtolnay** [comment]
I checked the explanation and I believe it is correct as written.
