### ISSUE TITLE
Q12 feedback : add a paragraph about "Field Init Shorthand"

### ISSUE THREAD

**Issue by Mazwak** [dtolnay/rust-quiz#8]
The hardest part with Q12 for me was why 'x' was in scope for the print.

After some research, I found https://doc.rust-lang.org/book/ch05-01-defining-structs.html#using-the-field-init-shorthand-when-variables-and-fields-have-the-same-name .

You might want to add it to the explanation.

**Comment by dtolnay** [comment]
Thanks! I added a link to an explanation of destructuring in 80a436a3ec39ba2f9c63b4b2b24265f4b8c3fc24.
